/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg27noward_rcc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Store_Info extends javax.swing.JFrame {
    public Connection connection;

    /**
     * Creates new form Store_Info
     */
    public Store_Info() {
        initComponents();
        connectDB();
        ViewData();
    }
    
      public void connectDB() {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=27NoWord;selectMethod=cursor", "sa", "123456");

            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    void Insert(){
            String area,sName,oName;
            int strID,oNID;
            area = jComboBoxArea.getSelectedItem().toString();
            oNID= Integer.valueOf(textFieldoNID.getText());
            sName=textFieldStoreName.getText();
            strID = Integer.valueOf(textFieldStoreID.getText());
            
            
        try {
            
        String sql = "INSERT INTO Stores ( Store_Name, Store_ID, Area) VALUES (?,?,?)";
            
        PreparedStatement ps = connection.prepareStatement(sql);
        ps.setString(1, sName);
        ps.setInt(2, strID);
        ps.setString(3, area);
             
        ps.executeUpdate();
        
        sql = "INSERT INTO Has ( NID_No, Store_ID) VALUES (?,?)";
            
        ps = connection.prepareStatement(sql);
        ps.setInt(1, oNID);
        ps.setInt(2, strID);
             
        ps.executeUpdate();
            
        JOptionPane.showMessageDialog(null, "Info Added ... ", "Info", JOptionPane.INFORMATION_MESSAGE);
        

            textFieldStoreName.setText("");
            textFieldStoreID.setText("");
            textFieldoNID.setText("");
            jComboBoxArea.setSelectedItem("Baliapukur");
        
       
    }
    catch (SQLException ex) {
            //Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went Wrong", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
     void Update(){
            String area,storeName;
            int storeID,oNid;
            area = jComboBoxArea.getSelectedItem().toString();
            oNid=Integer.parseInt(textFieldoNID.getText());
            storeName=textFieldStoreName.getText();
            storeID = Integer.valueOf(textFieldStoreID.getText());
            
            
        try {
            
           String sql;
           sql = "UPDATE Stores Set Store_Name= (?),Area=(?) Where Store_ID=(?)";
            
        PreparedStatement ps = connection.prepareStatement(sql);
            
        
        ps.setString(1, storeName);
        ps.setString(2, area);
        ps.setInt(3, storeID);
             
        ps.executeUpdate();
        sql = "INSERT INTO Has ( NID_No, Store_ID) VALUES (?,?)";
        ps = connection.prepareStatement(sql);
        
        ps.setInt(1, oNid);
        ps.setInt(2, storeID);
        
        ps.executeUpdate();
            
        JOptionPane.showMessageDialog(null, "Info Updated ... ", "Update Info", JOptionPane.INFORMATION_MESSAGE);
        
            textFieldStoreName.setText("");
            textFieldStoreID.setText("");
            textFieldoNID.setText("");
            jComboBoxArea.setSelectedItem("Baliapukur");
          textFieldStoreID.setEditable(true);
        
       
    }
    catch (SQLException ex) {
            //Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went Wrong.May be Wrong EIIN number", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    public void ViewData(){
        
        try {
            String query = "SELECT * FROM Stores Left Outer Join Has On Stores.Store_ID= Has.Store_ID Left Outer Join Citizens On Has.NID_No=Citizens.NID_No";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            String area,storeName,oName;
            int storeID;
            DefaultTableModel model = (DefaultTableModel)jTableStore.getModel();
            model.setRowCount(0);
            
            while(rs.next()){
                
                storeName = rs.getString("Store_Name");
                storeID = rs.getInt("Store_ID");
                area = rs.getString("Area");
                oName = rs.getString("Name");
                
                
                
                Object[] col = new Object[4];
                
                col[0] = storeName;
                col[1] = storeID;
                col[2] = oName;
                col[3] = area;
                
            
                model.addRow(col);
            }
        } catch (SQLException ex) {
            Logger.getLogger(House.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    void Delete(){
         String area,storeName;
            int storeID,oNid;
            area = jComboBoxArea.getSelectedItem().toString();
            oNid=Integer.parseInt(textFieldoNID.getText());
            storeName=textFieldStoreName.getText();
            storeID = Integer.valueOf(textFieldStoreID.getText());
            
        try {
                      String sql;
           sql = "Delete From Stores Where Store_ID=(?)";
            
        PreparedStatement ps = connection.prepareStatement(sql);
             
        ps.setInt(1, storeID); 
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Info Deleted ... ", "Delete Info", JOptionPane.INFORMATION_MESSAGE);
        
           textFieldStoreName.setText("");
            textFieldStoreID.setText("");
            textFieldoNID.setText("");
            jComboBoxArea.setSelectedItem("Baliapukur");
            textFieldStoreID.setEditable(true);
    }
    catch (SQLException ex) {
            //Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went Wrong.", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCitizens = new javax.swing.JButton();
        jButtonHouse = new javax.swing.JButton();
        jButtonEDU_INS = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxArea = new javax.swing.JComboBox<>();
        textFieldStoreID = new java.awt.TextField();
        textFieldStoreName = new java.awt.TextField();
        jButtonAdd = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStore = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        textFieldoNID = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("27 No Ward_RCC");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButtonCitizens.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCitizens.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCitizens.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCitizens.setText("CITIZENS");
        jButtonCitizens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCitizensActionPerformed(evt);
            }
        });

        jButtonHouse.setBackground(new java.awt.Color(0, 0, 0));
        jButtonHouse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonHouse.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHouse.setText("HOUSES");
        jButtonHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHouseActionPerformed(evt);
            }
        });

        jButtonEDU_INS.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEDU_INS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEDU_INS.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEDU_INS.setText("EDU_INS");
        jButtonEDU_INS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEDU_INSActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("© Monon_Mirza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCitizens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEDU_INS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButtonCitizens)
                .addGap(18, 18, 18)
                .addComponent(jButtonHouse)
                .addGap(18, 18, 18)
                .addComponent(jButtonEDU_INS)
                .addGap(325, 325, 325)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("INFO OF STORES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Store ID :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name of the Store :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Owner's NID :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Area :");

        jComboBoxArea.setForeground(new java.awt.Color(0, 102, 102));
        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baliapukur", "Vodra", "Debishing Para", "Monnafer Mor", "Shadhur Mor", "Mirer chok", "Tikapara", "Moth Pukur" }));

        textFieldStoreID.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        textFieldStoreID.setForeground(new java.awt.Color(0, 102, 102));
        textFieldStoreID.setText("13000");

        textFieldStoreName.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        textFieldStoreName.setForeground(new java.awt.Color(0, 102, 102));

        jButtonAdd.setBackground(new java.awt.Color(0, 102, 102));
        jButtonAdd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jTableStore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store Name", "Store ID", "Owner's Name", "Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableStore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableStoreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableStore);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel6.setText("STORES");

        textFieldoNID.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        textFieldoNID.setForeground(new java.awt.Color(0, 102, 102));
        textFieldoNID.setText("234567890");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(288, 288, 288))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldStoreID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldoNID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(textFieldStoreName, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldStoreName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textFieldStoreID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(textFieldoNID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButton5)
                    .addComponent(jButtonDelete))
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCitizensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCitizensActionPerformed
dispose();
        Citizens obj = new Citizens();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCitizensActionPerformed

    private void jButtonHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHouseActionPerformed
dispose();
        House obj = new House();
        obj.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHouseActionPerformed

    private void jButtonEDU_INSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEDU_INSActionPerformed
        // TODO add your handling code here:
        dispose();
        Edu_Ins obj = new Edu_Ins();
        obj.setVisible(true);
    }//GEN-LAST:event_jButtonEDU_INSActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        Insert();
   ViewData();
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Update();
   ViewData();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
 Delete();
      ViewData();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTableStoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableStoreMouseClicked
DefaultTableModel tblModel = (DefaultTableModel)jTableStore.getModel();
            String tblName= tblModel.getValueAt(jTableStore.getSelectedRow(),0).toString();
            String tblarea= tblModel.getValueAt(jTableStore.getSelectedRow(),3).toString();
            String tblstrID= tblModel.getValueAt(jTableStore.getSelectedRow(),1).toString();
            String tbloName= tblModel.getValueAt(jTableStore.getSelectedRow(),2).toString();
            

              textFieldStoreName.setText(tblName);
              textFieldStoreID.setText(tblstrID);
              jComboBoxArea.setSelectedItem(tblarea);
              //textFieldphn.setText(tblPhn);
              textFieldStoreID.setEditable(false);
              try {
            
        String sql = "Delete From Has Where Store_ID=(?)";
            
        PreparedStatement ps = connection.prepareStatement(sql);
            
        int str_id =Integer.parseInt(tblstrID);
        ps.setInt(1, str_id);
        ps.executeUpdate();
            
        //JOptionPane.showMessageDialog(null, "Info Added ... ", "Info", JOptionPane.INFORMATION_MESSAGE);

       
    }
    catch (SQLException ex) {
            //Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Something went Wrong", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
              // TODO add your handling code here:
            // TODO add your handling code here:
    }//GEN-LAST:event_jTableStoreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCitizens;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEDU_INS;
    private javax.swing.JButton jButtonHouse;
    private javax.swing.JComboBox<String> jComboBoxArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStore;
    private java.awt.TextField textFieldStoreID;
    private java.awt.TextField textFieldStoreName;
    private java.awt.TextField textFieldoNID;
    // End of variables declaration//GEN-END:variables
}
